// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwADxuDTcDCIitp5XJfMO_Wpgs3RZaqU',
    appId: '1:206802767874:web:dc3322adf81f0145ff971b',
    messagingSenderId: '206802767874',
    projectId: 'gui-nim-with-firebase',
    authDomain: 'gui-nim-with-firebase.firebaseapp.com',
    storageBucket: 'gui-nim-with-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlTK4l-mq56E6Y9XZFPRCzbanineP9S7k',
    appId: '1:206802767874:android:36eb962ea23880e7ff971b',
    messagingSenderId: '206802767874',
    projectId: 'gui-nim-with-firebase',
    storageBucket: 'gui-nim-with-firebase.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiwADxuDTcDCIitp5XJfMO_Wpgs3RZaqU',
    appId: '1:206802767874:web:62eaa14c8ae73d04ff971b',
    messagingSenderId: '206802767874',
    projectId: 'gui-nim-with-firebase',
    authDomain: 'gui-nim-with-firebase.firebaseapp.com',
    storageBucket: 'gui-nim-with-firebase.appspot.com',
  );
}
